// SPDX-License-Identifier: MIT
pragma solidity 0.8.18;

import {Test} from "forge-std/Test.sol";
import {ERC1967Proxy} from "openzeppelin-contracts/proxy/ERC1967/ERC1967Proxy.sol";

import {Cart} from "../../../../cart/Cart.sol";
import {CartHashes} from "../../../../cart/CartHashes.sol";
import {CartPayments} from "../../../../cart/CartPayments.sol";
import {CartRoutePolicy} from "../../../../cart/CartRoutePolicy.sol";
import {ICart} from "../../../../cart/ICart.sol";

interface IERC20Template {
    function approve(address spender, uint256 amount) external returns (bool);
    function allowance(address owner, address spender) external view returns (uint256);
    function balanceOf(address account) external view returns (uint256);
    function transfer(address to, uint256 amount) external returns (bool);
}

interface IWETHTemplate is IERC20Template {
    function deposit() external payable;
}

interface IPermit2Template {
    function approve(address token, address spender, uint160 amount, uint48 expiration) external;
    function allowance(address owner, address token, address spender)
        external
        view
        returns (uint160 amount, uint48 expiration, uint48 nonce);
}

interface IUniversalRouterTemplate {
    function execute(bytes calldata commands, bytes[] calldata inputs, uint256 deadline) external payable;
}

/// @notice Real Universal Router template checks against a pinned Ethereum Mainnet fork.
/// @dev These tests validate client-generated bytes against the deployed router. Cart's unit
///      suite owns custody, solvency, payout, spread, and allowance assertions around the same
///      opaque payload boundary. An archive-capable Ethereum RPC is required; createSelectFork
///      runs locally and does not broadcast transactions or require a testnet deployment.
contract CartUniversalRouterTemplatesEthereumTest is Test {
    uint256 private constant ETHEREUM_MAINNET = 1;
    uint256 private constant FORK_BLOCK = 25_800_000;

    address private constant PERMIT2 = 0x000000000022D473030F116dDEE9F6B43aC78BA3;
    address private constant UNIVERSAL_ROUTER = 0x66a9893cC07D91D95644AEDD05D03f95e1dBA8Af;
    address private constant WETH = 0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2;
    address private constant USDC = 0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48;
    address private constant DAI = 0x6B175474E89094C44Da98b954EedeAC495271d0F;
    address private constant V2_WETH_USDC = 0xB4e16d0168e52d35CaCD2c6185b44281Ec28C9Dc;
    address private constant V2_WETH_DAI = 0xA478c2975Ab1Ea89e8196811F51A7B7Ade33eB11;
    address private constant V3_WETH_USDC_500 = 0x88e6A0c2dDD26FEEb64F039a2c41296FcB3f5640;
    address private constant V3_WETH_DAI_3000 = 0xC2e9F25Be6257c210d7Adf0D4Cd6E3E881ba25f8;
    address private constant V4_POOL_MANAGER = 0x000000000004444c5dc75cB358380D2e3dE08A90;
    bytes32 private constant V4_ETH_USDC_POOL_ID =
        0x21c67e77068de97969ba93d4aab21826d33ca12bb9f565d8496e8fda8a82ca27;
    // The Universal Router deployment is immutable; this is the extcodehash pinned for the
    // deployment used by the fork templates. A changed deployment must update this test deliberately.
    bytes32 private constant UNIVERSAL_ROUTER_CODE_HASH =
        0x6a5f46971b50c6e1b7eef97902311444e479d734e4f80ad88367783cf373fe7f;

    IUniversalRouterTemplate private router;

    struct PoolKey {
        address currency0;
        address currency1;
        uint24 fee;
        int24 tickSpacing;
        address hooks;
    }

    struct V4ExactInputSingleParams {
        PoolKey poolKey;
        bool zeroForOne;
        uint128 amountIn;
        uint128 amountOutMinimum;
        bytes hookData;
    }

    struct V4ExactOutputSingleParams {
        PoolKey poolKey;
        bool zeroForOne;
        uint128 amountOut;
        uint128 amountInMaximum;
        bytes hookData;
    }

    function setUp() public {
        string memory rpcUrl = vm.envString("ETH_MAINNET_RPC_URL");
        vm.createSelectFork(rpcUrl, FORK_BLOCK);
        require(block.chainid == ETHEREUM_MAINNET, "This test must run on Ethereum Mainnet");
        assertEq(block.number, FORK_BLOCK, "Unexpected fork block");
        require(UNIVERSAL_ROUTER.code.length != 0, "Universal Router has no code");
        assertEq(UNIVERSAL_ROUTER.codehash, UNIVERSAL_ROUTER_CODE_HASH, "Unexpected Universal Router code hash");
        _assertPinnedFixtureAddresses();
        router = IUniversalRouterTemplate(UNIVERSAL_ROUTER);
        _assertPinnedFixturesHaveUsableLiquidity();
    }

    function testWrapAndUnwrapEthTemplate() public {
        uint256 amount = 0.01 ether;
        vm.deal(address(this), amount);
        uint256 beforeBalance = address(this).balance;
        uint256 beforeWeth = IWETHTemplate(WETH).balanceOf(address(this));

        bytes[] memory inputs = new bytes[](2);
        inputs[0] = abi.encode(address(2), amount);
        inputs[1] = abi.encode(address(1), amount);
        router.execute{value: amount}(hex"0b0c", inputs, block.timestamp + 1 days);

        assertEq(IWETHTemplate(WETH).balanceOf(address(this)), beforeWeth);
        assertEq(address(this).balance, beforeBalance);
    }

    function testV2ExactInputTemplate() public {
        uint256 amountIn = 0.001 ether;
        _fundRouterWithWeth(amountIn);
        uint256 beforeOutput = IERC20Template(USDC).balanceOf(address(this));

        address[] memory path = _path(WETH, USDC);
        bytes[] memory inputs = new bytes[](1);
        inputs[0] = abi.encode(address(1), amountIn, 1, path, false);
        router.execute(hex"08", inputs, block.timestamp + 1 days);

        assertGt(IERC20Template(USDC).balanceOf(address(this)), beforeOutput);
    }

    function testV3ExactInputTemplate() public {
        uint256 amountIn = 0.001 ether;
        _fundRouterWithWeth(amountIn);
        uint256 beforeOutput = IERC20Template(USDC).balanceOf(address(this));

        bytes memory path = abi.encodePacked(WETH, uint24(500), USDC);
        bytes[] memory inputs = new bytes[](1);
        inputs[0] = abi.encode(address(1), amountIn, 1, path, false);
        router.execute(hex"00", inputs, block.timestamp + 1 days);

        assertGt(IERC20Template(USDC).balanceOf(address(this)), beforeOutput);
    }

    function testV2ExactOutputRefundSweepTemplate() public {
        uint256 maxInput = 0.01 ether;
        _fundRouterWithWeth(maxInput);
        uint256 beforeOutput = IERC20Template(USDC).balanceOf(address(this));

        address[] memory path = _path(WETH, USDC);
        bytes[] memory inputs = new bytes[](2);
        inputs[0] = abi.encode(address(1), 1_000_000, maxInput, path, false);
        inputs[1] = abi.encode(WETH, address(1), 0);
        router.execute(hex"0904", inputs, block.timestamp + 1 days);

        assertGt(IERC20Template(USDC).balanceOf(address(this)), beforeOutput);
        assertGt(IWETHTemplate(WETH).balanceOf(address(this)), 0);
    }

    function testV3ExactOutputRefundSweepTemplate() public {
        uint256 maxInput = 0.01 ether;
        _fundRouterWithWeth(maxInput);
        uint256 beforeOutput = IERC20Template(USDC).balanceOf(address(this));

        // V3 exact-output paths are encoded in reverse order.
        bytes memory path = abi.encodePacked(USDC, uint24(500), WETH);
        bytes[] memory inputs = new bytes[](2);
        inputs[0] = abi.encode(address(1), 1_000_000, maxInput, path, false);
        inputs[1] = abi.encode(WETH, address(1), 0);
        router.execute(hex"0104", inputs, block.timestamp + 1 days);

        assertGt(IERC20Template(USDC).balanceOf(address(this)), beforeOutput);
        assertGt(IWETHTemplate(WETH).balanceOf(address(this)), 0);
    }

    function testV4NativeEthToUsdcTemplate() public {
        uint256 amountIn = 0.001 ether;
        vm.deal(address(this), amountIn);
        uint256 beforeOutput = IERC20Template(USDC).balanceOf(address(this));

        V4ExactInputSingleParams memory swap = V4ExactInputSingleParams({
            poolKey: PoolKey({currency0: address(0), currency1: USDC, fee: 500, tickSpacing: 10, hooks: address(0)}),
            zeroForOne: true,
            amountIn: uint128(amountIn),
            amountOutMinimum: 1,
            hookData: bytes("")
        });
        bytes memory actions = hex"060c0f";
        bytes[] memory params = new bytes[](3);
        params[0] = abi.encode(swap);
        params[1] = abi.encode(address(0), amountIn);
        params[2] = abi.encode(USDC, 1);
        bytes[] memory inputs = new bytes[](1);
        inputs[0] = abi.encode(actions, params);
        router.execute{value: amountIn}(hex"10", inputs, block.timestamp + 1 days);

        assertGt(IERC20Template(USDC).balanceOf(address(this)), beforeOutput);
    }

    function testV4Erc20ToNativeExactOutputTemplate() public {
        _obtainUsdc();
        uint256 maxInput = IERC20Template(USDC).balanceOf(address(this));
        require(maxInput != 0, "V2 template returned no USDC");
        IERC20Template(USDC).approve(PERMIT2, maxInput);
        IPermit2Template(PERMIT2).approve(USDC, UNIVERSAL_ROUTER, uint160(maxInput), uint48(block.timestamp + 1 days));
        uint256 beforeOutput = address(this).balance;

        V4ExactOutputSingleParams memory swap = V4ExactOutputSingleParams({
            poolKey: PoolKey({currency0: address(0), currency1: USDC, fee: 500, tickSpacing: 10, hooks: address(0)}),
            zeroForOne: false,
            amountOut: uint128(0.0005 ether),
            amountInMaximum: uint128(maxInput),
            hookData: bytes("")
        });
        bytes memory actions = hex"080c0f";
        bytes[] memory params = new bytes[](3);
        params[0] = abi.encode(swap);
        params[1] = abi.encode(USDC, maxInput);
        params[2] = abi.encode(address(0), 0.0005 ether);
        bytes[] memory inputs = new bytes[](1);
        inputs[0] = abi.encode(actions, params);
        router.execute(hex"10", inputs, block.timestamp + 1 days);

        assertGe(address(this).balance, beforeOutput + 0.0005 ether);
    }

    function _fundRouterWithWeth(uint256 amount) private {
        vm.deal(address(this), amount);
        IWETHTemplate(WETH).deposit{value: amount}();
        require(IWETHTemplate(WETH).transfer(UNIVERSAL_ROUTER, amount), "WETH transfer failed");
    }

    function _obtainUsdc() private {
        _fundRouterWithWeth(0.01 ether);
        address[] memory path = _path(WETH, USDC);
        bytes[] memory inputs = new bytes[](1);
        inputs[0] = abi.encode(address(1), 0.01 ether, 1, path, false);
        router.execute(hex"08", inputs, block.timestamp + 1 days);
    }

    function _path(address first, address second) private pure returns (address[] memory path) {
        path = new address[](2);
        path[0] = first;
        path[1] = second;
    }

    function _assertPinnedFixtureAddresses() private {
        assertGt(V2_WETH_USDC.code.length, 0, "Pinned V2 WETH/USDC pair has no code");
        assertGt(V2_WETH_DAI.code.length, 0, "Pinned V2 WETH/DAI pair has no code");
        assertGt(V3_WETH_USDC_500.code.length, 0, "Pinned V3 WETH/USDC pool has no code");
        assertGt(V3_WETH_DAI_3000.code.length, 0, "Pinned V3 WETH/DAI pool has no code");
        assertGt(V4_POOL_MANAGER.code.length, 0, "Pinned V4 PoolManager has no code");

        PoolKey memory poolKey = PoolKey({
            currency0: address(0), currency1: USDC, fee: 500, tickSpacing: 10, hooks: address(0)
        });
        assertEq(keccak256(abi.encode(poolKey)), V4_ETH_USDC_POOL_ID, "Unexpected V4 ETH/USDC pool id");
    }

    function _assertPinnedFixturesHaveUsableLiquidity() private {
        uint256 amountIn = 0.0001 ether;

        _fundRouterWithWeth(amountIn);
        _executeFixtureProbe(
            hex"08",
            _singleInput(abi.encode(address(1), amountIn, 1, _path(WETH, USDC), false)),
            "Pinned V2 WETH/USDC fixture has no usable liquidity"
        );

        _fundRouterWithWeth(amountIn);
        _executeFixtureProbe(
            hex"08",
            _singleInput(abi.encode(address(1), amountIn, 1, _path(WETH, DAI), false)),
            "Pinned V2 WETH/DAI fixture has no usable liquidity"
        );

        _fundRouterWithWeth(amountIn);
        _executeFixtureProbe(
            hex"00",
            _singleInput(abi.encode(address(1), amountIn, 1, abi.encodePacked(WETH, uint24(500), USDC), false)),
            "Pinned V3 WETH/USDC fixture has no usable liquidity"
        );

        _fundRouterWithWeth(amountIn);
        _executeFixtureProbe(
            hex"00",
            _singleInput(abi.encode(address(1), amountIn, 1, abi.encodePacked(WETH, uint24(3000), DAI), false)),
            "Pinned V3 WETH/DAI fixture has no usable liquidity"
        );

        vm.deal(address(this), amountIn);
        _executeFixtureProbe(
            hex"10", _singleInput(_v4NativeExactInput(amountIn)), "Pinned V4 ETH/USDC fixture has no usable liquidity", amountIn
        );
    }

    function _executeFixtureProbe(bytes memory commands, bytes[] memory inputs, string memory failureMessage) private {
        _executeFixtureProbe(commands, inputs, failureMessage, 0);
    }

    function _executeFixtureProbe(
        bytes memory commands, bytes[] memory inputs, string memory failureMessage, uint256 value
    ) private {
        (bool success,) = UNIVERSAL_ROUTER.call{value: value}(
            abi.encodeCall(IUniversalRouterTemplate.execute, (commands, inputs, block.timestamp + 1 days))
        );
        require(success, failureMessage);
    }

    function _singleInput(bytes memory input) private pure returns (bytes[] memory inputs) {
        inputs = new bytes[](1);
        inputs[0] = input;
    }

    function _v4NativeExactInput(uint256 amount) private pure returns (bytes memory input) {
        V4ExactInputSingleParams memory swap = V4ExactInputSingleParams({
            poolKey: PoolKey({currency0: address(0), currency1: USDC, fee: 500, tickSpacing: 10, hooks: address(0)}),
            zeroForOne: true,
            amountIn: uint128(amount),
            amountOutMinimum: 1,
            hookData: bytes("")
        });
        bytes memory actions = hex"060c0f";
        bytes[] memory params = new bytes[](3);
        params[0] = abi.encode(swap);
        params[1] = abi.encode(address(0), amount);
        params[2] = abi.encode(USDC, 1);
        return abi.encode(actions, params);
    }

    receive() external payable {}
}

/// @notice End-to-end Cart execution against the deployed Universal Router.
/// @dev The client route bytes remain opaque to Cart. These tests prove that real router outputs,
/// refunds, and native conversions cross the Cart custody boundary and still settle exact lines.
contract CartUniversalRouterCartEthereumTest is Test {
    uint256 private constant ETHEREUM_MAINNET = 1;
    uint256 private constant FORK_BLOCK = 25_800_000;
    uint256 private constant PLATFORM_PK = 0xA11CE;

    address private constant PERMIT2 = 0x000000000022D473030F116dDEE9F6B43aC78BA3;
    address private constant UNIVERSAL_ROUTER = 0x66a9893cC07D91D95644AEDD05D03f95e1dBA8Af;
    address private constant WETH = 0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2;
    address private constant USDC = 0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48;
    address private constant DAI = 0x6B175474E89094C44Da98b954EedeAC495271d0F;
    address private constant V2_WETH_USDC = 0xB4e16d0168e52d35CaCD2c6185b44281Ec28C9Dc;
    address private constant V2_WETH_DAI = 0xA478c2975Ab1Ea89e8196811F51A7B7Ade33eB11;
    address private constant V3_WETH_USDC_500 = 0x88e6A0c2dDD26FEEb64F039a2c41296FcB3f5640;
    address private constant V3_WETH_DAI_3000 = 0xC2e9F25Be6257c210d7Adf0D4Cd6E3E881ba25f8;
    address private constant V4_POOL_MANAGER = 0x000000000004444c5dc75cB358380D2e3dE08A90;
    bytes32 private constant V4_ETH_USDC_POOL_ID =
        0x21c67e77068de97969ba93d4aab21826d33ca12bb9f565d8496e8fda8a82ca27;
    bytes32 private constant UNIVERSAL_ROUTER_CODE_HASH =
        0x6a5f46971b50c6e1b7eef97902311444e479d734e4f80ad88367783cf373fe7f;

    Cart private cart;
    CartHashes private hashes;
    IUniversalRouterTemplate private router;

    struct PoolKey {
        address currency0;
        address currency1;
        uint24 fee;
        int24 tickSpacing;
        address hooks;
    }

    struct V4ExactInputSingleParams {
        PoolKey poolKey;
        bool zeroForOne;
        uint128 amountIn;
        uint128 amountOutMinimum;
        bytes hookData;
    }

    function setUp() public {
        string memory rpcUrl = vm.envString("ETH_MAINNET_RPC_URL");
        vm.createSelectFork(rpcUrl, FORK_BLOCK);
        require(block.chainid == ETHEREUM_MAINNET, "This test must run on Ethereum Mainnet");
        assertEq(block.number, FORK_BLOCK, "Unexpected fork block");
        require(UNIVERSAL_ROUTER.code.length != 0, "Universal Router has no code");
        assertEq(UNIVERSAL_ROUTER.codehash, UNIVERSAL_ROUTER_CODE_HASH, "Unexpected Universal Router code hash");
        _assertPinnedFixtureAddresses();
        router = IUniversalRouterTemplate(UNIVERSAL_ROUTER);
        _assertPinnedFixturesHaveUsableLiquidity();

        CartRoutePolicy routePolicy = new CartRoutePolicy();
        CartPayments paymentExecutor = new CartPayments(address(routePolicy));
        Cart implementation = new Cart(address(routePolicy), address(paymentExecutor));
        bytes memory initData = abi.encodeCall(
            Cart.initialize, (address(this), vm.addr(PLATFORM_PK), UNIVERSAL_ROUTER, PERMIT2, WETH)
        );
        cart = Cart(payable(address(new ERC1967Proxy(address(implementation), initData))));
        hashes = new CartHashes();
    }

    function testCartDirectEthV3DaiAndV4UsdcPlan() public {
        uint256 directAmount = 0.001 ether;
        uint256 v3Amount = 0.001 ether;
        uint256 v4Amount = 0.001 ether;
        ICart.PayoutRoute memory route = _nativeV3V4Route(v3Amount, v4Amount);
        ICart.OrderLine[] memory lines = new ICart.OrderLine[](3);
        lines[0] = _directLine(address(0), directAmount, address(0x1001), "direct-eth");
        lines[1] = _currencyLine(DAI, 1, address(0x1002), "v3-dai");
        lines[2] = _currencyLine(USDC, 1, address(0x1003), "v4-usdc");

        uint256 usdcBefore = IERC20Template(USDC).balanceOf(address(this));
        uint256 daiBefore = IERC20Template(DAI).balanceOf(address(this));
        uint256 cartEthBaseline = address(cart).balance;
        uint256 cartWethBaseline = IERC20Template(WETH).balanceOf(address(cart));
        uint256 cartUsdcBaseline = IERC20Template(USDC).balanceOf(address(cart));
        uint256 cartDaiBaseline = IERC20Template(DAI).balanceOf(address(cart));
        uint256 directBefore = address(0x1001).balance;
        uint256 usdcRecipientBefore = IERC20Template(USDC).balanceOf(address(0x1003));
        uint256 daiRecipientBefore = IERC20Template(DAI).balanceOf(address(0x1002));
        uint256 protocolUsdcBefore = usdcBefore;
        uint256 protocolDaiBefore = daiBefore;
        uint256 quote = directAmount + v3Amount + v4Amount;

        vm.deal(address(this), quote);
        _executeNative("cart-direct-eth-v3-v4", quote, lines, route);

        assertEq(address(0x1001).balance, directBefore + directAmount);
        assertEq(IERC20Template(DAI).balanceOf(address(0x1002)), daiRecipientBefore + 1);
        assertEq(IERC20Template(USDC).balanceOf(address(0x1003)), usdcRecipientBefore + 1);
        assertGt(IERC20Template(USDC).balanceOf(address(this)), protocolUsdcBefore);
        assertGt(IERC20Template(DAI).balanceOf(address(this)), protocolDaiBefore);
        _assertCartBaselines(cartEthBaseline, cartWethBaseline, cartUsdcBaseline, cartDaiBaseline);
    }

    function testCartRealRouterPositiveOutputShortfallReverts() public {
        uint256 amountIn = 0.001 ether;
        uint256 snapshotId = vm.snapshot();
        ICart.PayoutRoute memory quoteRoute = _nativeV3DaiToRecipientRoute(amountIn, address(1));
        uint256 beforeOutput = IERC20Template(DAI).balanceOf(address(this));
        vm.deal(address(this), amountIn);
        router.execute{value: amountIn}(
            quoteRoute.commands, quoteRoute.inputs, block.timestamp + 1 days
        );
        uint256 actualOutput = IERC20Template(DAI).balanceOf(address(this)) - beforeOutput;
        assertGt(actualOutput, 0, "Pinned V3 quote returned no DAI");
        assertTrue(vm.revertTo(snapshotId));

        ICart.PayoutRoute memory route = _nativeV3DaiToRecipientRoute(amountIn, address(1));
        ICart.OrderLine[] memory lines = new ICart.OrderLine[](1);
        lines[0] = _currencyLine(DAI, actualOutput + 1 ether, address(0x1401), "real-router-output-shortfall");
        ICart.FulfillmentAction[] memory actions = new ICart.FulfillmentAction[](0);
        uint256 quote = amountIn;
        ICart.PurchaseOrder memory order = _order("real-router-output-shortfall", address(0), quote, lines, route);
        bytes memory signature = _sign(_orderDigest(order));

        vm.deal(address(this), quote);
        vm.expectRevert(
            abi.encodeWithSelector(
                ICart.OrderLineFailed.selector,
                0,
                ICart.FailureStage.ROUTING,
                abi.encode(actualOutput, actualOutput + 1 ether)
            )
        );
        cart.executePurchase{value: quote}(
            order,
            lines,
            new ICart.Listing[](0),
            _emptyAuthorization(),
            route,
            actions,
            signature
        );

        assertFalse(cart.executedOrderIds(order.orderId));
        assertEq(address(this).balance, quote);
        assertEq(IERC20Template(DAI).balanceOf(address(0x1401)), 0);
    }

    function testCartMixedV2V3V4Plan() public {
        uint256 directAmount = 0.001 ether;
        uint256 v2Amount = 0.001 ether;
        uint256 v3Amount = 0.001 ether;
        uint256 v4Amount = 0.001 ether;
        ICart.PayoutRoute memory route = _nativeV2V3V4Route(v2Amount, v3Amount, v4Amount);
        ICart.OrderLine[] memory lines = new ICart.OrderLine[](3);
        lines[0] = _directLine(address(0), directAmount, address(0x1101), "mixed-direct-eth");
        lines[1] = _currencyLine(USDC, 2, address(0x1102), "mixed-usdc");
        lines[2] = _currencyLine(DAI, 1, address(0x1103), "mixed-dai");
        uint256 quote = directAmount + v2Amount + v3Amount + v4Amount;
        uint256 directBefore = address(0x1101).balance;
        uint256 usdcRecipientBefore = IERC20Template(USDC).balanceOf(address(0x1102));
        uint256 daiRecipientBefore = IERC20Template(DAI).balanceOf(address(0x1103));

        vm.deal(address(this), quote);
        _executeNative("cart-mixed-v2-v3-v4", quote, lines, route);

        assertEq(address(0x1101).balance, directBefore + directAmount);
        assertEq(IERC20Template(USDC).balanceOf(address(0x1102)), usdcRecipientBefore + 2);
        assertEq(IERC20Template(DAI).balanceOf(address(0x1103)), daiRecipientBefore + 1);
        _assertCartBaselines(0, 0, 0, 0);
    }

    function testCartWethTransferUnwrapAndNativeV4Route() public {
        uint256 amount = 0.001 ether;
        ICart.PayoutRoute memory route = _wethToNativeV4Route(amount);
        ICart.OrderLine[] memory lines = new ICart.OrderLine[](1);
        lines[0] = _currencyLine(USDC, 1, address(0x1201), "weth-native-v4");
        uint256 wethBefore = IERC20Template(WETH).balanceOf(address(cart));
        uint256 usdcBefore = IERC20Template(USDC).balanceOf(address(cart));
        uint256 recipientBefore = IERC20Template(USDC).balanceOf(address(0x1201));

        vm.deal(address(this), amount);
        IWETHTemplate(WETH).deposit{value: amount}();
        IERC20Template(WETH).approve(address(cart), amount);
        _executeErc20("cart-weth-transfer-unwrap-v4", WETH, amount, lines, route);

        assertEq(IERC20Template(USDC).balanceOf(address(0x1201)), recipientBefore + 1);
        assertEq(IERC20Template(WETH).balanceOf(address(cart)), wethBefore);
        assertEq(IERC20Template(USDC).balanceOf(address(cart)), usdcBefore);
        assertEq(IERC20Template(WETH).allowance(address(cart), PERMIT2), 0);
        (uint160 amountAfter,,) = IPermit2Template(PERMIT2).allowance(address(cart), WETH, UNIVERSAL_ROUTER);
        assertEq(amountAfter, 0);
    }

    function testCartV3ExactOutputRefundBecomesProtocolSpread() public {
        uint256 maxInput = 0.01 ether;
        uint256 outputAmount = 1_000_000;
        ICart.PayoutRoute memory route = _wethV3ExactOutputRoute(maxInput, outputAmount);
        ICart.OrderLine[] memory lines = new ICart.OrderLine[](1);
        lines[0] = _currencyLine(USDC, outputAmount, address(0x1301), "v3-exact-output");
        uint256 protocolBefore = IERC20Template(WETH).balanceOf(address(this));
        uint256 recipientBefore = IERC20Template(USDC).balanceOf(address(0x1301));

        vm.deal(address(this), maxInput);
        IWETHTemplate(WETH).deposit{value: maxInput}();
        IERC20Template(WETH).approve(address(cart), maxInput);
        _executeErc20("cart-v3-exact-output", WETH, maxInput, lines, route);

        assertEq(IERC20Template(USDC).balanceOf(address(0x1301)), recipientBefore + outputAmount);
        assertGt(IERC20Template(WETH).balanceOf(address(this)), protocolBefore);
        assertEq(IERC20Template(WETH).balanceOf(address(cart)), 0);
        assertEq(IERC20Template(WETH).allowance(address(cart), PERMIT2), 0);
        (uint160 amountAfter,,) = IPermit2Template(PERMIT2).allowance(address(cart), WETH, UNIVERSAL_ROUTER);
        assertEq(amountAfter, 0);
    }

    function _executeNative(
        string memory id,
        uint256 quote,
        ICart.OrderLine[] memory lines,
        ICart.PayoutRoute memory route
    ) private {
        ICart.PurchaseOrder memory order = _order(id, address(0), quote, lines, route);
        cart.executePurchase{value: quote}(
            order,
            lines,
            new ICart.Listing[](0),
            _emptyAuthorization(),
            route,
            new ICart.FulfillmentAction[](0),
            _sign(_orderDigest(order))
        );
    }

    function _executeErc20(
        string memory id,
        address paymentCurrency,
        uint256 quote,
        ICart.OrderLine[] memory lines,
        ICart.PayoutRoute memory route
    ) private {
        ICart.PurchaseOrder memory order = _order(id, paymentCurrency, quote, lines, route);
        cart.executePurchase(
            order,
            lines,
            new ICart.Listing[](0),
            _emptyAuthorization(),
            route,
            new ICart.FulfillmentAction[](0),
            _sign(_orderDigest(order))
        );
    }

    function _order(
        string memory id,
        address paymentCurrency,
        uint256 quote,
        ICart.OrderLine[] memory lines,
        ICart.PayoutRoute memory route
    ) private view returns (ICart.PurchaseOrder memory order) {
        ICart.FulfillmentAction[] memory actions = new ICart.FulfillmentAction[](0);
        order = ICart.PurchaseOrder({
            orderId: keccak256(bytes(id)),
            paymentCurrency: paymentCurrency,
            deadline: block.timestamp + 1 days,
            paymentAmount: quote,
            orderLinesHash: hashes.hashOrderLines(lines),
            payoutRouteHash: hashes.hashPayoutRoute(route),
            fulfillmentActionsHash: hashes.hashFulfillmentActions(actions)
        });
    }

    function _currencyLine(address currency, uint256 amount, address recipient, string memory id)
        private
        pure
        returns (ICart.OrderLine memory line)
    {
        line = ICart.OrderLine({
            sku: keccak256(bytes(id)),
            listingHash: bytes32(0),
            fulfillmentKind: ICart.FulfillmentKind.CURRENCY_SWAP,
            quantity: 1,
            settlementCurrency: currency,
            amount: amount,
            paymentRecipient: recipient
        });
    }

    function _directLine(address currency, uint256 amount, address recipient, string memory id)
        private
        pure
        returns (ICart.OrderLine memory line)
    {
        line = ICart.OrderLine({
            sku: keccak256(bytes(id)),
            listingHash: bytes32(0),
            fulfillmentKind: ICart.FulfillmentKind.NONE,
            quantity: 1,
            settlementCurrency: currency,
            amount: amount,
            paymentRecipient: recipient
        });
    }

    function _nativeV3V4Route(uint256 v3Amount, uint256 v4Amount)
        private
        pure
        returns (ICart.PayoutRoute memory route)
    {
        route.commands = hex"0b0010";
        route.inputs = new bytes[](3);
        route.inputs[0] = abi.encode(address(2), v3Amount);
        route.inputs[1] = abi.encode(address(1), v3Amount, 1, abi.encodePacked(WETH, uint24(3000), DAI), false);
        route.inputs[2] = _v4NativeExactInput(v4Amount);
        route.routerValue = v3Amount + v4Amount;
    }

    function _nativeV3DaiToRecipientRoute(uint256 amount, address recipient)
        private
        pure
        returns (ICart.PayoutRoute memory route)
    {
        route.commands = hex"0b00";
        route.inputs = new bytes[](2);
        route.inputs[0] = abi.encode(address(2), amount);
        route.inputs[1] = abi.encode(
            recipient, amount, 1, abi.encodePacked(WETH, uint24(3000), DAI), false
        );
        route.routerValue = amount;
    }

    function _nativeV2V3V4Route(uint256 v2Amount, uint256 v3Amount, uint256 v4Amount)
        private
        pure
        returns (ICart.PayoutRoute memory route)
    {
        route.commands = hex"0b080010";
        route.inputs = new bytes[](4);
        route.inputs[0] = abi.encode(address(2), v2Amount + v3Amount);
        route.inputs[1] = abi.encode(address(1), v2Amount, 1, _path(WETH, USDC), false);
        route.inputs[2] = abi.encode(address(1), v3Amount, 1, abi.encodePacked(WETH, uint24(3000), DAI), false);
        route.inputs[3] = _v4NativeExactInput(v4Amount);
        route.routerValue = v2Amount + v3Amount + v4Amount;
    }

    function _wethToNativeV4Route(uint256 amount) private pure returns (ICart.PayoutRoute memory route) {
        route.commands = hex"020c10";
        route.inputs = new bytes[](3);
        route.inputs[0] = abi.encode(WETH, address(2), uint160(amount));
        route.inputs[1] = abi.encode(address(2), amount);
        route.inputs[2] = _v4NativeExactInput(amount);
    }

    function _wethV3ExactOutputRoute(uint256 maxInput, uint256 outputAmount)
        private
        pure
        returns (ICart.PayoutRoute memory route)
    {
        route.commands = hex"020104";
        route.inputs = new bytes[](3);
        route.inputs[0] = abi.encode(WETH, address(2), uint160(maxInput));
        route.inputs[1] = abi.encode(
            address(1), outputAmount, maxInput, abi.encodePacked(USDC, uint24(500), WETH), false
        );
        route.inputs[2] = abi.encode(WETH, address(1), 0);
    }

    function _v4NativeExactInput(uint256 amount) private pure returns (bytes memory input) {
        V4ExactInputSingleParams memory swap = V4ExactInputSingleParams({
            poolKey: PoolKey({currency0: address(0), currency1: USDC, fee: 500, tickSpacing: 10, hooks: address(0)}),
            zeroForOne: true,
            amountIn: uint128(amount),
            amountOutMinimum: 1,
            hookData: bytes("")
        });
        bytes memory actions = hex"060c0f";
        bytes[] memory params = new bytes[](3);
        params[0] = abi.encode(swap);
        params[1] = abi.encode(address(0), amount);
        params[2] = abi.encode(USDC, 1);
        return abi.encode(actions, params);
    }

    function _path(address first, address second) private pure returns (address[] memory path) {
        path = new address[](2);
        path[0] = first;
        path[1] = second;
    }

    function _assertPinnedFixtureAddresses() private {
        assertGt(V2_WETH_USDC.code.length, 0, "Pinned V2 WETH/USDC pair has no code");
        assertGt(V2_WETH_DAI.code.length, 0, "Pinned V2 WETH/DAI pair has no code");
        assertGt(V3_WETH_USDC_500.code.length, 0, "Pinned V3 WETH/USDC pool has no code");
        assertGt(V3_WETH_DAI_3000.code.length, 0, "Pinned V3 WETH/DAI pool has no code");
        assertGt(V4_POOL_MANAGER.code.length, 0, "Pinned V4 PoolManager has no code");

        PoolKey memory poolKey = PoolKey({
            currency0: address(0), currency1: USDC, fee: 500, tickSpacing: 10, hooks: address(0)
        });
        assertEq(keccak256(abi.encode(poolKey)), V4_ETH_USDC_POOL_ID, "Unexpected V4 ETH/USDC pool id");
    }

    function _assertPinnedFixturesHaveUsableLiquidity() private {
        uint256 amountIn = 0.0001 ether;

        _fundRouterWithWeth(amountIn);
        _executeFixtureProbe(
            hex"08",
            _singleInput(abi.encode(address(1), amountIn, 1, _path(WETH, USDC), false)),
            "Pinned V2 WETH/USDC fixture has no usable liquidity"
        );

        _fundRouterWithWeth(amountIn);
        _executeFixtureProbe(
            hex"08",
            _singleInput(abi.encode(address(1), amountIn, 1, _path(WETH, DAI), false)),
            "Pinned V2 WETH/DAI fixture has no usable liquidity"
        );

        _fundRouterWithWeth(amountIn);
        _executeFixtureProbe(
            hex"00",
            _singleInput(abi.encode(address(1), amountIn, 1, abi.encodePacked(WETH, uint24(500), USDC), false)),
            "Pinned V3 WETH/USDC fixture has no usable liquidity"
        );

        _fundRouterWithWeth(amountIn);
        _executeFixtureProbe(
            hex"00",
            _singleInput(abi.encode(address(1), amountIn, 1, abi.encodePacked(WETH, uint24(3000), DAI), false)),
            "Pinned V3 WETH/DAI fixture has no usable liquidity"
        );

        vm.deal(address(this), amountIn);
        _executeFixtureProbe(
            hex"10", _singleInput(_v4NativeExactInput(amountIn)), "Pinned V4 ETH/USDC fixture has no usable liquidity", amountIn
        );
    }

    function _fundRouterWithWeth(uint256 amount) private {
        vm.deal(address(this), amount);
        IWETHTemplate(WETH).deposit{value: amount}();
        require(IWETHTemplate(WETH).transfer(UNIVERSAL_ROUTER, amount), "WETH transfer failed");
    }

    function _executeFixtureProbe(bytes memory commands, bytes[] memory inputs, string memory failureMessage) private {
        _executeFixtureProbe(commands, inputs, failureMessage, 0);
    }

    function _executeFixtureProbe(
        bytes memory commands, bytes[] memory inputs, string memory failureMessage, uint256 value
    ) private {
        (bool success,) = UNIVERSAL_ROUTER.call{value: value}(
            abi.encodeCall(IUniversalRouterTemplate.execute, (commands, inputs, block.timestamp + 1 days))
        );
        require(success, failureMessage);
    }

    function _singleInput(bytes memory input) private pure returns (bytes[] memory inputs) {
        inputs = new bytes[](1);
        inputs[0] = input;
    }

    function _emptyAuthorization() private pure returns (ICart.ListingPurchaseAuthorization memory authorization) {
        authorization.listingRoots = new ICart.ListingRoot[](0);
        authorization.listingRootSignatures = new bytes[](0);
        authorization.listingRootIndexes = new uint256[](0);
        authorization.listingProofs = new bytes32[][](0);
    }

    function _orderDigest(ICart.PurchaseOrder memory order) private view returns (bytes32) {
        return hashes.hashOrder(cart.DOMAIN_SEPARATOR(), order);
    }

    function _sign(bytes32 digest) private returns (bytes memory signature) {
        (uint8 v, bytes32 r, bytes32 s) = vm.sign(PLATFORM_PK, digest);
        return abi.encodePacked(r, s, v);
    }

    function _assertCartBaselines(uint256 ethBaseline, uint256 wethBaseline, uint256 usdcBaseline, uint256 daiBaseline)
        private
    {
        assertEq(address(cart).balance, ethBaseline);
        assertEq(IERC20Template(WETH).balanceOf(address(cart)), wethBaseline);
        assertEq(IERC20Template(USDC).balanceOf(address(cart)), usdcBaseline);
        assertEq(IERC20Template(DAI).balanceOf(address(cart)), daiBaseline);
        assertEq(IERC20Template(WETH).allowance(address(cart), PERMIT2), 0);
        (uint160 amount,,) = IPermit2Template(PERMIT2).allowance(address(cart), WETH, UNIVERSAL_ROUTER);
        assertEq(amount, 0);
    }

    receive() external payable {}
}
